name: Compile

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - name: Download a single artifact
        uses: actions/download-artifact@v2
      - run: yarn start
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: data-files
          path: |
            data
