name: Compile

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: data
          key: primes
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn start
      - run: yarn run chart-data
